const initialNotes = [
  {
    id: null,
    title: 'React Markdown',
    body: '# React Router\n\nReact router is [available in here](https://reactrouter.com)\n\n## How to Install\n\nInstall React Router: `npm i react-router-dom`\n\n### Introduction\n\nStrikethrough text: ~~This is a strikethrough text~~\n\nItalic text: _This is an italic text_\n\nBold text: __This is a bold text__\n\n> This is a blockquote text\n\nBelow is a table:\n\n|   Nation    |   State   |   City    |\n|     --      |    --     |    --     |\n|  Indonesia  | West Java |  Bandung  |\n\n```jsx\nexport default function AppPage() {\n  return (\n    <h1>Hello, world!</h1>\n  );\n}\n```',
    createdAt: '2023-12-17T13:27:44.031Z',
    archived: false,
    owner: null,
  },
  {
    id: null,
    title: 'Babel',
    body: 'Babel merupakan tools open-source yang digunakan untuk mengubah sintaks ECMAScript 2015+ menjadi sintaks yang didukung oleh JavaScript engine versi lama. Babel sering dipakai ketika kita menggunakan sintaks terbaru termasuk sintaks JSX.',
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
    owner: null,
  },
  {
    id: null,
    title: 'Functional Component',
    body: 'Functional component merupakan React component yang dibuat menggunakan fungsi JavaScript. Agar fungsi JavaScript dapat disebut component ia harus mengembalikan React element dan dipanggil layaknya React component.',
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
    owner: null,
  },
  {
    id: null,
    title: 'Lifecycle',
    body: 'Dalam konteks React component, lifecycle merupakan kumpulan method yang menjadi siklus hidup mulai dari component dibuat (constructor), dicetak (render), pasca-cetak (componentDidMount), dan sebagainya. ',
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
    owner: null,
  },
  {
    id: null,
    title: 'ESM',
    body: 'ESM (ECMAScript Module) merupakan format modularisasi standar JavaScript.',
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
    owner: null,
  },
  {
    id: null,
    title: 'Module Bundler',
    body: 'Dalam konteks pemrograman JavaScript, module bundler merupakan tools yang digunakan untuk menggabungkan seluruh modul JavaScript yang digunakan oleh aplikasi menjadi satu berkas.',
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: false,
    owner: null,
  },
  {
    id: null,
    title: 'Function Component in React Web Framework',
    body: 'React Function Component adalah jenis React component yang memiliki syntax yang lebih simple dan memungkinkan kita untuk menggunakan React Hooks.',
    createdAt: '2023-12-16T07:10:42.041Z',
    archived: true,
    owner: null,
  },
  {
    id: null,
    title: 'Modularization',
    body: 'Dalam konteks pemrograman JavaScript, modularization merupakan teknik dalam memecah atau menggunakan kode dalam berkas JavaScript secara terpisah berdasarkan tanggung jawabnya masing-masing.',
    createdAt: '2022-04-14T04:27:34.572Z',
    archived: true,
    owner: null,
  },
];

export default initialNotes;
